apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Metadata for this overlay
metadata:
  name: mailhog-prod

# Reference to the base configuration
resources:
  - ../../base

# Namespace for production environment
namespace: mailhog-prod

# Name prefix for all resources in prod
namePrefix: prod-

# Additional labels specific to prod environment
commonLabels:
  environment: production
  tier: stable

# Resource customizations for prod
patchesStrategicMerge:
  - replica-patch.yaml
  - security-patch.yaml

# ConfigMap generator for prod-specific config
configMapGenerator:
  - name: mailhog-config
    literals:
      - environment=production
      - log-level=info
      - retention-days=7

# Images with specific tags for production
images:
  - name: mailhog/mailhog
    newTag: v1.0.1  # Pinned version for production stability