apiVersion: v1
kind: Service
metadata:
  name: mailhog
  labels:
    app: mailhog
spec:
  selector:
    app: mailhog
  type: NodePort
  ports:
  - name: smtp
    port: 1025        # Port exposed within the cluster
    targetPort: 1025  # Port on the container
    nodePort: 31025   # Port accessible from outside the cluster
  - name: web
    port: 8025        # Port exposed within the cluster
    targetPort: 8025  # Port on the container
    nodePort: 31080   # Port accessible from outside the cluster